# @package trainer

_target_: "pytorch_lightning.trainer.Trainer"

accelerator: null
accumulate_grad_batches: 1
benchmark: false
detect_anomaly: false
deterministic: false
enable_checkpointing: ${save}
enable_model_summary: false
fast_dev_run: false
gpus: ${gpus}
gradient_clip_algorithm: "norm"
gradient_clip_val: 10
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
max_epochs: ${epochs}
max_steps: -1
move_metrics_to_cpu: true
# precision: 32, 16
precision: 32
# profiler: null, 'simple', 'advanced', 'pytorch'
profiler: null
resume_from_checkpoint: null
track_grad_norm: -1
