# @package audio_trans

_target_: "dcase2022task6a.transforms.get.get_resample_spectro_mean"

src_sr: ${data.sr}
tgt_sr: 32000

window_size: 1024
hop_size: 320
mel_bins: 64
fmin: 50
fmax: 14000
window: 'hann'
center: true
pad_mode: 'reflect'
ref: 1.0
amin: 1e-10
top_db: null
freeze_parameters: true

mean_dim: 0
