# @package audio_trans

_target_: "dcase2022task6a.transforms.audio.spec_aug.SpecAugmentation"

# defaults params used in https://github.com/XinhaoMei/DCASE2021_task6_v2/blob/7f2464fb9c2bfeb60cf0328fdd2378658451c141/models/Encoder.py#L120 :
# time_drop_width: 64
# time_stripes_num: 2
# freq_drop_width: 8
# freq_stripes_num: 2

time_drop_width: 64
time_stripes_num: 2
freq_drop_width: 2
freq_stripes_num: 1
p: 1.0
